--ALTER TABLE Seasons
--ADD Identifier INT NOT NULL;

--CREATE TABLE UserTeamSquads (
--	Id INT PRIMARY KEY,
--	GK1_Id INT NOT NULL,
--	GK2_Id INT NOT NULL,
--	DF1_Id INT NOT NULL,
--	DF2_Id INT NOT NULL,
--	DF3_Id INT NOT NULL,
--	DF4_Id INT NOT NULL,
--	DF5_Id INT NOT NULL,
--	MF1_Id INT NOT NULL,
--	MF2_Id INT NOT NULL,
--	MF3_Id INT NOT NULL,
--	MF4_Id INT NOT NULL,
--	MF5_Id INT NOT NULL,
--	AT1_Id INT NOT NULL,
--	AT2_Id INT NOT NULL,
--	AT3_Id INT NOT NULL,
--	AT4_Id INT NOT NULL,
--	UserTeamId INT NOT NULL,
--	FOREIGN KEY (UserTeamId) REFERENCES UserTeams(Id) ON DELETE CASCADE
--);

--CREATE TABLE Players (
--	Id INT PRIMARY KEY,
--	FirstName NVARCHAR(50),
--	LastName NVARCHAR(50),
--	BirthDate NVARCHAR(20),
--	Nationality NVARCHAR(50),
--	Height NVARCHAR(10),
--	Photo NVARCHAR(100),
--	TeamId INT NOT NULL
--);

--CREATE TABLE Teams (
--	Id INT PRIMARY KEY,
--	Name NVARCHAR(50),
--	Logo NVARCHAR(100),
--  LeagueId INT NOT NULL
--);

--CREATE TABLE Leagues (
--	Id INT PRIMARY KEY,
--	Name NVARCHAR(50),
--	Logo NVARCHAR(100),
--	Flag NVARCHAR(100)
--);

--ALTER TABLE Teams
--	ADD FOREIGN KEY (LeagueId) REFERENCES Leagues(Id) ON DELETE CASCADE; 

--ALTER TABLE Players
--	ADD FOREIGN KEY (TeamId) REFERENCES Teams(Id) ON DELETE CASCADE;